FROM node:12.18.1
ENV NODE_ENV=production

RUN mkdir -p /usr/share/messenger-bot
WORKDIR /usr/share/messenger-bot

RUN rm -rf node_modules/
COPY ["package.json", "package-lock.json*", "./"]
RUN npm install --production
COPY . .

EXPOSE 3000
CMD [ "npm", "start" ]